### ISSUE TITLE
Offspring Data table schema

### ISSUE THREAD

**Issue by Kshatrapati** [KshitizGIT/ZedRunner#1]
Hello Kshitiz,

Hope you are doing good. Thank you for creating such a wonderful API. It is helping me a lot for sure. While, I have been able to populate data following your codes here, I am stuck at one place. There is supposed to be one more table created in SQL & i.e. on Offspring Data which can be populated using below command in VB.

pipenv run python zed.py --type offspring

However, there is no table schema available for it in READ.me. Please help with the same so that the table can be created first and then we can populate the data using above command.

In addition to your codes, below video on youtube has helped practically implement it please.

https://www.youtube.com/watch?v=pF2k22vaSCo&t=961s

Looking forward for your response.

Thank you again!

**Comment by Kshatrapati** [comment]
.

**Comment by KshitizGIT** [comment]
I don't think I have implemented this. But if you are looking at the fork https://github.com/ttruty/ZedRunner. Fetching the offspring data only updates the horses table.

**Comment by Kshatrapati** [comment]
Thank you for the response Kshitij. I understand it now. There is one more thing which I would like to highlight and request your comments at your convenience please. When I am running pipenv run python zed.py --type stable it gives an error keyword: parents. I went to the mapper file and the relevant code is:

parents_father= d['parents']['father']
            parents_father_id = None
            if parents_father:
                parents_father_id = parents_father['horse_id']
            parents_mother= d['parents']['mother']
            parents_mother_id = None
            if parents_mother:
                parents_mother_id = parents_mother['horse_id']

To deal with this error, what ttruty has done is, he has inserted exceptions, please find below the code. However, the problem with this approach is that there is no data coming for parent_father & parent_mother in the sql. Not sure if it is due to this exception or in the source itself these data points are not there.

parents_father_id = None
            parents_mother_id = None
            try:
                parents_father= d['parents']['father']
                parents_father_id = None
                if parents_father:
                    parents_father_id = parents_father['horse_id']
            except:
                parents_father_id = None

            try:
                parents_mother= d['parents']['mother']
                parents_mother_id = None
                if parents_mother:
                    parents_mother_id = parents_mother['horse_id']
            except:
                parents_mother_id = None

Please help.
